##
# Ansible playbook for setting up an Ubuntu based Workstation
#
---
- hosts: local
  become: no

  vars_files:
    - settings.yml

  pre_tasks:
    - name: create /bin/src/tmp dir
      file: path="{{item}}" state=directory mode=0755
      with_items:
        - ~/bin
        - ~/src
        - ~/pkg
        - ~/tmp
        - ~/.config

  roles:
    - dotfiles                        # Must be first
    - aussielunix.python
    - capotej.packagecloud
    - direnv
    - dropbox
    - googlechrome
    - libreoffice
    - lubuntu
    - mkdocs
    - misc                            # generic role / dumping ground
    - ntp
    - rbenv                           # install rbenv and ruby
    - slack
    - terminator
    - vagrant
    - vim                             # vim + vim dotfiles
    - virtualbox
