---

- hosts: localhost
  sudo: false
  vars_files:
    - settings.yml
  pre_tasks:
    - name: create bin/src/pkg/tmp dir
      file: path="{{item}}" state=directory mode=0755
      with_items:
        - ~/bin
        - ~/src
        - ~/pkg
        - ~/tmp
  roles:
    - pajuna.dotfiles
    - pajuna.vim
