---

- hosts: localhost
  sudo: false
  vars_files:
    - settings.yml
  pre_tasks:
    - name: create bin/src/pkg/tmp dir
      file: path="{{item}}" state=directory mode=0755
      with_items:
        - ~/bin
        - ~/src
        - ~/pkg
        - ~/tmp
    - name: git clone/pull dotfiles
      git: >
        repo={{dotfiles_repo}}
        dest={{dotfiles_dir}}
        accept_hostkey=yes
      tags: dotfiles

    - name: link various generic dotfiles into place
      file:
        src="{{dotfiles_dir}}/{{item}}"
        dest="{{lookup('env','HOME')}}/{{item}}"
        state=link
        force=yes
      with_items: dotfiles_files
      tags: dotfiles
