# my workstation specific settings.

---

user: pajuna
vimrc_repo: "git@github.com:pajuna/vimrc.git"

dotfiles_repo: git@github.com:pajuna/dotfiles.git
dotfiles_files:
  - .bash_alias
  - .profile
  - .bashrc
  - .profile.d
  - .bash_logout

rbenv_ruby_versions:
  - 2.2.3
rbenv_default_ruby_version: 2.2.3

misc_packages:
  - curl
  - git
