---

dotfiles_repo: "git@bitbucket.org:aussielunix/dotfiles.git"
dotfiles_repo_local_destination: "~/src/bitbucket.org/aussielunix/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .alias
