#!/bin/bash
# vim: autoindent tabstop=2 shiftwidth=2 expandtab softtabstop=2 filetype=sh

if [[ -d ~/.pajuna/upstream && ! -L ~/.pajuna/upstream ]]
then
  echo -e "\033[0;32mThe folder ".pajuna/upstream" already exists. Aborting.\033[0m"
  exit 1
else
  if ! hash pip 2>/dev/null
  then
    echo -e "\033[0;32m Installing python and python-pip.......\033[0m"
    sudo -E DEBIAN_FRONTEND=noninteractive apt-get -qq update
	  sudo -E DEBIAN_FRONTEND=noninteractive apt-get -qq install python python-pip python-dev < /dev/null > /dev/null
  fi

  if ! hash ansible 2>/dev/null
  then
    echo -e "\033[0;32m Adding the Ansible PPA.......\033[0m"
    sudo -E DEBIAN_FRONTEND=noninteractive apt-get -qq install software-properties-common < /dev/null > /dev/null
    sudo apt-add-repository -yu ppa:ansible/ansible
    echo -e "\033[0;32m installing Ansible from PPA.......\033[0m"
    sudo -E DEBIAN_FRONTEND=noninteractive apt-get -qq install ansible < /dev/null > /dev/null
  fi

  mkdir -p ~/.pajuna/upstream ~/.pajuna/myfork
  echo -e "\033[0;32m Cloning https://github.com/pajuna/Ubuntu-LTS.git to ~/.pajuna/upstream .......\033[0m"
  git clone https://github.com/pajuna/Ubuntu-LTS.git ~/.pajuna/upstream
fi


alias pajuna='ANSIBLE_CONFIG=~/.ansible/ansible.cfg ansible-playbook -i ~/.ansible/inventory ~/.ansible/playbook.yml'

# echo out welcome message etc
echo
echo -e "\033[0;36mBootstrap is complete....\033[0m"
exit 0
